apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/gustavo-jenkins-days-2018/jenkinx2019:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/gustavo-jenkins-days-2018/jenkinx2019:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jenkinx2019
        chartPath: charts/jenkinx2019
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/gustavo-jenkins-days-2018/jenkinx2019'
          image.tag: '{{.DIGEST_HEX}}'
